name: Flutter Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Change directory to Flutter project
        working-directory: ./vgc 
        run: echo "Changed working directory to my_flutter_app"

      - name: Install dependencies
        working-directory: ./vgc
        run: flutter pub get

      - name: Run Flutter tests
        working-directory: ./vgc
        run: flutter test
